"""first revision

Revision ID: 0e7ce4f55c8f
Revises: 
Create Date: 2023-03-20 00:20:40.840528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0e7ce4f55c8f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "application",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_application_id"), "application", ["id"], unique=False)
    op.create_table(
        "review",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_review_id"), "review", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_review_id"), table_name="review")
    op.drop_table("review")
    op.drop_index(op.f("ix_application_id"), table_name="application")
    op.drop_table("application")
    # ### end Alembic commands ###
