"""add policy path, last updated

Revision ID: 0f4c5a23b16f
Revises: db597300d845
Create Date: 2023-07-29 15:11:30.513203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0f4c5a23b16f"
down_revision = "db597300d845"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gplay_app", sa.Column("policy_updated", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "gplay_app", sa.Column("privacy_policy_path", sa.String(), nullable=True)
    )
    op.drop_column("gplay_app", "privacy_policy_html")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gplay_app",
        sa.Column(
            "privacy_policy_html", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("gplay_app", "privacy_policy_path")
    op.drop_column("gplay_app", "policy_updated")
    # ### end Alembic commands ###
