"""second revision

Revision ID: 56c45d1626e1
Revises: a276b50eb7e9
Create Date: 2023-04-10 02:28:47.911437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "56c45d1626e1"
down_revision = "a276b50eb7e9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "appstore_app", ["app_id"])
    op.create_unique_constraint(None, "appstore_review", ["review_id"])
    op.alter_column(
        "gplay_app",
        "min_installs",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.alter_column(
        "gplay_app",
        "real_installs",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.alter_column(
        "gplay_app",
        "num_ratings",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.alter_column(
        "gplay_app",
        "num_reviews",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.create_unique_constraint(None, "gplay_app", ["app_id"])
    op.alter_column(
        "gplay_review",
        "thumbs_up_count",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.create_unique_constraint(None, "gplay_review", ["review_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "gplay_review", type_="unique")
    op.alter_column(
        "gplay_review",
        "thumbs_up_count",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.drop_constraint(None, "gplay_app", type_="unique")
    op.alter_column(
        "gplay_app",
        "num_reviews",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "gplay_app",
        "num_ratings",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "gplay_app",
        "real_installs",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "gplay_app",
        "min_installs",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.drop_constraint(None, "appstore_review", type_="unique")
    op.drop_constraint(None, "appstore_app", type_="unique")
    # ### end Alembic commands ###
