"""first revision

Revision ID: a276b50eb7e9
Revises: 
Create Date: 2023-04-03 01:17:14.182033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a276b50eb7e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appstore_app',
    sa.Column('app_id', sa.String(), nullable=False),
    sa.Column('app_name', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('rights', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('app_uri', sa.String(), nullable=True),
    sa.Column('app_bundle', sa.String(), nullable=True),
    sa.Column('artist', sa.String(), nullable=True),
    sa.Column('artist_uri', sa.String(), nullable=True),
    sa.Column('app_category_id', sa.String(), nullable=True),
    sa.Column('app_category_name', sa.String(), nullable=True),
    sa.Column('app_category_uri', sa.String(), nullable=True),
    sa.Column('app_release_date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('app_id'),
    sa.UniqueConstraint('app_id')
    )
    op.create_table('gplay_app',
    sa.Column('app_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('installs', sa.String(), nullable=True),
    sa.Column('min_installs', sa.Integer(), nullable=True),
    sa.Column('real_installs', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('num_ratings', sa.Integer(), nullable=True),
    sa.Column('num_reviews', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('free', sa.Boolean(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('sale', sa.String(), nullable=True),
    sa.Column('developer', sa.String(), nullable=True),
    sa.Column('developer_id', sa.String(), nullable=True),
    sa.Column('developer_email', sa.String(), nullable=True),
    sa.Column('developer_website', sa.String(), nullable=True),
    sa.Column('privacy_policy', sa.String(), nullable=True),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('genre_id', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('header_image', sa.String(), nullable=True),
    sa.Column('video', sa.String(), nullable=True),
    sa.Column('video_image', sa.String(), nullable=True),
    sa.Column('content_rating', sa.String(), nullable=True),
    sa.Column('ad_supported', sa.Boolean(), nullable=True),
    sa.Column('contains_ads', sa.Boolean(), nullable=True),
    sa.Column('released', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('app_id'),
    sa.UniqueConstraint('app_id')
    )
    op.create_table('appstore_review',
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('review_uri', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('review_version', sa.String(), nullable=True),
    sa.Column('review_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('vote_sum', sa.Integer(), nullable=True),
    sa.Column('vote_count', sa.Integer(), nullable=True),
    sa.Column('app_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['appstore_app.app_id'], ),
    sa.PrimaryKeyConstraint('review_id'),
    sa.UniqueConstraint('review_id')
    )
    op.create_table('gplay_review',
    sa.Column('review_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('user_image', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('thumbs_up_count', sa.Integer(), nullable=True),
    sa.Column('review_created_version', sa.String(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('reply_content', sa.String(), nullable=True),
    sa.Column('reply_at', sa.DateTime(), nullable=True),
    sa.Column('app_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['gplay_app.app_id'], ),
    sa.PrimaryKeyConstraint('review_id'),
    sa.UniqueConstraint('review_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gplay_review')
    op.drop_table('appstore_review')
    op.drop_table('gplay_app')
    op.drop_table('appstore_app')
    # ### end Alembic commands ###
