"""second revision

Revision ID: c51de85a94c0
Revises: 0e7ce4f55c8f
Create Date: 2023-03-26 07:06:32.078464

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c51de85a94c0"
down_revision = "0e7ce4f55c8f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("application", sa.Column("app_id", sa.String(), nullable=False))
    op.add_column("application", sa.Column("title", sa.String(), nullable=True))
    op.add_column("application", sa.Column("description", sa.String(), nullable=True))
    op.add_column("application", sa.Column("summary", sa.String(), nullable=True))
    op.add_column("application", sa.Column("installs", sa.String(), nullable=True))
    op.add_column("application", sa.Column("min_installs", sa.Integer(), nullable=True))
    op.add_column(
        "application", sa.Column("real_installs", sa.Integer(), nullable=True)
    )
    op.add_column("application", sa.Column("score", sa.Float(), nullable=True))
    op.add_column("application", sa.Column("num_ratings", sa.Integer(), nullable=True))
    op.add_column("application", sa.Column("num_reviews", sa.Integer(), nullable=True))
    op.add_column("application", sa.Column("price", sa.Float(), nullable=True))
    op.add_column("application", sa.Column("free", sa.Boolean(), nullable=True))
    op.add_column("application", sa.Column("currency", sa.String(), nullable=True))
    op.add_column("application", sa.Column("sale", sa.String(), nullable=True))
    op.add_column("application", sa.Column("developer", sa.String(), nullable=True))
    op.add_column("application", sa.Column("developer_id", sa.String(), nullable=True))
    op.add_column(
        "application", sa.Column("developer_email", sa.String(), nullable=True)
    )
    op.add_column(
        "application", sa.Column("developer_website", sa.String(), nullable=True)
    )
    op.add_column(
        "application", sa.Column("privacy_policy", sa.String(), nullable=True)
    )
    op.add_column("application", sa.Column("genre", sa.String(), nullable=True))
    op.add_column("application", sa.Column("genre_id", sa.String(), nullable=True))
    op.add_column("application", sa.Column("icon", sa.String(), nullable=True))
    op.add_column("application", sa.Column("header_image", sa.String(), nullable=True))
    op.add_column("application", sa.Column("video", sa.String(), nullable=True))
    op.add_column("application", sa.Column("video_image", sa.String(), nullable=True))
    op.add_column(
        "application", sa.Column("content_rating", sa.String(), nullable=True)
    )
    op.add_column("application", sa.Column("ad_supported", sa.Boolean(), nullable=True))
    op.add_column("application", sa.Column("contains_ads", sa.Boolean(), nullable=True))
    op.add_column("application", sa.Column("released", sa.DateTime(), nullable=True))
    op.add_column("application", sa.Column("updated", sa.DateTime(), nullable=True))
    op.add_column("application", sa.Column("version", sa.String(), nullable=True))
    op.add_column("application", sa.Column("url", sa.String(), nullable=True))
    op.drop_index("ix_application_id", table_name="application")
    op.create_unique_constraint(None, "application", ["app_id"])
    op.drop_column("application", "id")
    op.add_column("review", sa.Column("review_id", sa.String(), nullable=False))
    op.add_column("review", sa.Column("username", sa.String(), nullable=True))
    op.add_column("review", sa.Column("user_image", sa.String(), nullable=True))
    op.add_column("review", sa.Column("content", sa.String(), nullable=True))
    op.add_column("review", sa.Column("score", sa.Integer(), nullable=True))
    op.add_column("review", sa.Column("thumbs_up_count", sa.Integer(), nullable=True))
    op.add_column(
        "review", sa.Column("review_created_version", sa.String(), nullable=True)
    )
    op.add_column("review", sa.Column("posted_at", sa.DateTime(), nullable=True))
    op.add_column("review", sa.Column("reply_content", sa.String(), nullable=True))
    op.add_column("review", sa.Column("reply_at", sa.DateTime(), nullable=True))
    op.add_column("review", sa.Column("app_id", sa.String(), nullable=True))
    op.drop_index("ix_review_id", table_name="review")
    op.create_unique_constraint(None, "review", ["review_id"])
    op.create_foreign_key(None, "review", "application", ["app_id"], ["app_id"])
    op.drop_column("review", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "review", sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False)
    )
    op.drop_constraint(None, "review", type_="foreignkey")
    op.drop_constraint(None, "review", type_="unique")
    op.create_index("ix_review_id", "review", ["id"], unique=False)
    op.drop_column("review", "app_id")
    op.drop_column("review", "reply_at")
    op.drop_column("review", "reply_content")
    op.drop_column("review", "posted_at")
    op.drop_column("review", "review_created_version")
    op.drop_column("review", "thumbs_up_count")
    op.drop_column("review", "score")
    op.drop_column("review", "content")
    op.drop_column("review", "user_image")
    op.drop_column("review", "username")
    op.drop_column("review", "review_id")
    op.add_column(
        "application", sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False)
    )
    op.drop_constraint(None, "application", type_="unique")
    op.create_index("ix_application_id", "application", ["id"], unique=False)
    op.drop_column("application", "url")
    op.drop_column("application", "version")
    op.drop_column("application", "updated")
    op.drop_column("application", "released")
    op.drop_column("application", "contains_ads")
    op.drop_column("application", "ad_supported")
    op.drop_column("application", "content_rating")
    op.drop_column("application", "video_image")
    op.drop_column("application", "video")
    op.drop_column("application", "header_image")
    op.drop_column("application", "icon")
    op.drop_column("application", "genre_id")
    op.drop_column("application", "genre")
    op.drop_column("application", "privacy_policy")
    op.drop_column("application", "developer_website")
    op.drop_column("application", "developer_email")
    op.drop_column("application", "developer_id")
    op.drop_column("application", "developer")
    op.drop_column("application", "sale")
    op.drop_column("application", "currency")
    op.drop_column("application", "free")
    op.drop_column("application", "price")
    op.drop_column("application", "num_reviews")
    op.drop_column("application", "num_ratings")
    op.drop_column("application", "score")
    op.drop_column("application", "real_installs")
    op.drop_column("application", "min_installs")
    op.drop_column("application", "installs")
    op.drop_column("application", "summary")
    op.drop_column("application", "description")
    op.drop_column("application", "title")
    op.drop_column("application", "app_id")
    # ### end Alembic commands ###
