"""privacy policy content

Revision ID: db597300d845
Revises: f0b2ebe9e08a
Create Date: 2023-07-29 14:51:27.813209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "db597300d845"
down_revision = "f0b2ebe9e08a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gplay_app", sa.Column("privacy_policy_text", sa.String(), nullable=True)
    )
    op.add_column(
        "gplay_app", sa.Column("privacy_policy_html", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("gplay_app", "privacy_policy_html")
    op.drop_column("gplay_app", "privacy_policy_text")
    # ### end Alembic commands ###
